"""Curated database of common HPDE/track-day cars with manufacturer specs.

Provides lookup and search functions over a static collection of ~74 well-known
track-day vehicles spanning sports cars, muscle cars, hot hatches, and sedans.
Each entry carries real manufacturer specs for weight, wheelbase, power, and
drivetrain, plus estimated CG height and track width from published data.
"""

from __future__ import annotations

from dataclasses import dataclass

# ---------------------------------------------------------------------------
# Dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VehicleSpec:
    """Manufacturer specs for a car model.

    All dimensions are in SI units (kg, meters).  CG height uses published
    estimates (0.45-0.55 m for sports cars, 0.55-0.65 m for sedans/hatches).
    """

    make: str
    model: str
    generation: str  # e.g. "ND" for Miata, "E46" for M3
    year_range: tuple[int, int]  # (start_year, end_year)
    weight_kg: float
    wheelbase_m: float
    track_width_front_m: float
    track_width_rear_m: float
    cg_height_m: float  # ~0.45-0.55 m for sports cars
    weight_dist_front_pct: float  # 0-100
    drivetrain: str  # "RWD" | "FWD" | "AWD"
    hp: int
    torque_nm: int
    has_aero: bool
    cd_a: float = 0.0  # Cd * frontal_area (m²); 0.0 = unknown
    cl_a: float = 0.0  # CL * frontal_area (m²) for downforce; 0.0 = no downforce
    stock_tire_size_front: str | None = None  # e.g. "205/45R17"; OEM stock size
    stock_tire_size_rear: str | None = None  # same as front for square setups
    notes: str | None = None
    power_band_factor: float = 0.90  # fraction of peak power available across RPM range


# ---------------------------------------------------------------------------
# Curated vehicle database
# ---------------------------------------------------------------------------

VEHICLE_DATABASE: dict[str, VehicleSpec] = {
    # -----------------------------------------------------------------------
    # Mazda Miata
    # -----------------------------------------------------------------------
    "mazda_miata_na": VehicleSpec(
        make="Mazda",
        model="Miata",
        generation="NA",
        year_range=(1990, 1997),
        weight_kg=960,
        wheelbase_m=2.265,
        track_width_front_m=1.405,
        track_width_rear_m=1.420,
        cg_height_m=0.46,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=116,
        torque_nm=136,
        has_aero=False,
        cd_a=0.65,
        stock_tire_size_front="185/60R14",
        stock_tire_size_rear="185/60R14",
        notes="1.6 L B6-ZE. Lightest Miata generation.",
        power_band_factor=0.85,
    ),
    "mazda_miata_nb": VehicleSpec(
        make="Mazda",
        model="Miata",
        generation="NB",
        year_range=(1999, 2005),
        weight_kg=1030,
        wheelbase_m=2.265,
        track_width_front_m=1.410,
        track_width_rear_m=1.420,
        cg_height_m=0.46,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=142,
        torque_nm=162,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="185/60R14",
        stock_tire_size_rear="185/60R14",
        notes="1.8 L BP-4W. Refined NA platform.",
        power_band_factor=0.85,
    ),
    "mazda_miata_nc": VehicleSpec(
        make="Mazda",
        model="Miata",
        generation="NC",
        year_range=(2006, 2015),
        weight_kg=1130,
        wheelbase_m=2.330,
        track_width_front_m=1.490,
        track_width_rear_m=1.495,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=167,
        torque_nm=190,
        has_aero=False,
        cd_a=0.64,
        stock_tire_size_front="205/50R16",
        stock_tire_size_rear="205/50R16",
        notes="2.0 L MZR. Larger and heavier than NB.",
        power_band_factor=0.85,
    ),
    "mazda_miata_nd": VehicleSpec(
        make="Mazda",
        model="Miata",
        generation="ND",
        year_range=(2016, 2025),
        weight_kg=1058,
        wheelbase_m=2.310,
        track_width_front_m=1.496,
        track_width_rear_m=1.500,
        cg_height_m=0.45,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=181,
        torque_nm=205,
        has_aero=False,
        cd_a=0.56,
        stock_tire_size_front="195/50R16",
        stock_tire_size_rear="195/50R16",
        notes="2.0 L Skyactiv-G. Returns to lightweight roots.",
        power_band_factor=0.85,
    ),
    # -----------------------------------------------------------------------
    # Honda
    # -----------------------------------------------------------------------
    "honda_civic_si_10th": VehicleSpec(
        make="Honda",
        model="Civic Si",
        generation="FC",
        year_range=(2017, 2021),
        weight_kg=1293,
        wheelbase_m=2.700,
        track_width_front_m=1.533,
        track_width_rear_m=1.547,
        cg_height_m=0.53,
        weight_dist_front_pct=62.0,
        drivetrain="FWD",
        hp=205,
        torque_nm=260,
        has_aero=False,
        cd_a=0.64,
        stock_tire_size_front="235/40R18",
        stock_tire_size_rear="235/40R18",
        notes="1.5 L turbo. Popular budget HPDE car.",
    ),
    "honda_civic_type_r_fk8": VehicleSpec(
        make="Honda",
        model="Civic Type R",
        generation="FK8",
        year_range=(2017, 2021),
        weight_kg=1395,
        wheelbase_m=2.700,
        track_width_front_m=1.587,
        track_width_rear_m=1.565,
        cg_height_m=0.51,
        weight_dist_front_pct=62.0,
        drivetrain="FWD",
        hp=306,
        torque_nm=400,
        has_aero=True,
        cd_a=0.77,
        cl_a=0.20,
        stock_tire_size_front="245/30R20",
        stock_tire_size_rear="245/30R20",
        notes="2.0 L K20C1 turbo. Functional rear wing.",
    ),
    "honda_civic_type_r_fl5": VehicleSpec(
        make="Honda",
        model="Civic Type R",
        generation="FL5",
        year_range=(2023, 2025),
        weight_kg=1426,
        wheelbase_m=2.735,
        track_width_front_m=1.586,
        track_width_rear_m=1.565,
        cg_height_m=0.51,
        weight_dist_front_pct=61.0,
        drivetrain="FWD",
        hp=315,
        torque_nm=420,
        has_aero=True,
        cd_a=0.77,
        cl_a=0.25,
        stock_tire_size_front="265/35R19",
        stock_tire_size_rear="265/35R19",
        notes="2.0 L K20C1 turbo revised. Improved aero.",
        power_band_factor=0.82,
    ),
    "honda_s2000_ap1": VehicleSpec(
        make="Honda",
        model="S2000",
        generation="AP1",
        year_range=(1999, 2003),
        weight_kg=1260,
        wheelbase_m=2.400,
        track_width_front_m=1.470,
        track_width_rear_m=1.510,
        cg_height_m=0.46,
        weight_dist_front_pct=50.0,
        drivetrain="RWD",
        hp=240,
        torque_nm=208,
        has_aero=False,
        cd_a=0.61,
        stock_tire_size_front="205/55R16",
        stock_tire_size_rear="225/50R16",
        notes="2.0 L F20C, 9000 RPM redline.",
        power_band_factor=0.80,
    ),
    # -----------------------------------------------------------------------
    # Subaru / Toyota 86
    # -----------------------------------------------------------------------
    "toyota_86_zn6": VehicleSpec(
        make="Toyota",
        model="86",
        generation="ZN6",
        year_range=(2012, 2020),
        weight_kg=1235,
        wheelbase_m=2.570,
        track_width_front_m=1.520,
        track_width_rear_m=1.540,
        cg_height_m=0.46,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=200,
        torque_nm=205,
        has_aero=False,
        cd_a=0.52,
        stock_tire_size_front="215/45R17",
        stock_tire_size_rear="215/45R17",
        notes="2.0 L FA20. Also sold as Subaru BRZ / Scion FR-S.",
    ),
    "toyota_gr86_zn8": VehicleSpec(
        make="Toyota",
        model="GR86",
        generation="ZN8",
        year_range=(2022, 2025),
        weight_kg=1270,
        wheelbase_m=2.575,
        track_width_front_m=1.520,
        track_width_rear_m=1.550,
        cg_height_m=0.46,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=228,
        torque_nm=249,
        has_aero=False,
        cd_a=0.54,
        stock_tire_size_front="215/45R17",
        stock_tire_size_rear="215/45R17",
        notes="2.4 L FA24. Also sold as Subaru BRZ.",
    ),
    # -----------------------------------------------------------------------
    # Chevrolet Corvette
    # -----------------------------------------------------------------------
    "chevrolet_corvette_c5": VehicleSpec(
        make="Chevrolet",
        model="Corvette",
        generation="C5",
        year_range=(1997, 2004),
        weight_kg=1460,
        wheelbase_m=2.654,
        track_width_front_m=1.506,
        track_width_rear_m=1.521,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=345,
        torque_nm=475,
        has_aero=False,
        cd_a=0.57,
        stock_tire_size_front="245/45R17",
        stock_tire_size_rear="275/40R18",
        notes="5.7 L LS1. Budget track car bargain.",
    ),
    "chevrolet_corvette_c6": VehicleSpec(
        make="Chevrolet",
        model="Corvette",
        generation="C6",
        year_range=(2005, 2013),
        weight_kg=1460,
        wheelbase_m=2.686,
        track_width_front_m=1.556,
        track_width_rear_m=1.560,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=430,
        torque_nm=575,
        has_aero=False,
        cd_a=0.58,
        stock_tire_size_front="245/40R18",
        stock_tire_size_rear="285/35R19",
        notes="6.2 L LS3 (424 lb-ft). Exposed headlights.",
    ),
    "chevrolet_corvette_c7": VehicleSpec(
        make="Chevrolet",
        model="Corvette",
        generation="C7",
        year_range=(2014, 2019),
        weight_kg=1496,
        wheelbase_m=2.710,
        track_width_front_m=1.575,
        track_width_rear_m=1.585,
        cg_height_m=0.47,
        weight_dist_front_pct=50.0,
        drivetrain="RWD",
        hp=455,
        torque_nm=624,
        has_aero=False,
        cd_a=0.60,
        stock_tire_size_front="245/40R18",
        stock_tire_size_rear="285/35R19",
        notes="6.2 L LT1 (460 lb-ft). Last front-engine Corvette.",
    ),
    "chevrolet_corvette_c8": VehicleSpec(
        make="Chevrolet",
        model="Corvette",
        generation="C8",
        year_range=(2020, 2025),
        weight_kg=1530,
        wheelbase_m=2.723,
        track_width_front_m=1.583,
        track_width_rear_m=1.597,
        cg_height_m=0.45,
        weight_dist_front_pct=40.0,
        drivetrain="RWD",
        hp=495,
        torque_nm=637,
        has_aero=False,
        cd_a=0.61,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="305/30R20",
        notes="6.2 L LT2 base (470 lb-ft). Mid-engine layout.",
    ),
    "chevrolet_corvette_c8_z51": VehicleSpec(
        make="Chevrolet",
        model="Corvette Z51",
        generation="C8",
        year_range=(2020, 2025),
        weight_kg=1530,
        wheelbase_m=2.723,
        track_width_front_m=1.583,
        track_width_rear_m=1.597,
        cg_height_m=0.45,
        weight_dist_front_pct=40.0,
        drivetrain="RWD",
        hp=495,
        torque_nm=637,
        has_aero=True,
        cd_a=0.63,
        cl_a=0.30,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="305/30R20",
        notes="Z51 package: front splitter, rear spoiler, perf suspension, e-LSD.",
    ),
    "chevrolet_corvette_c6_z06": VehicleSpec(
        make="Chevrolet",
        model="Corvette Z06",
        generation="C6",
        year_range=(2006, 2013),
        weight_kg=1418,
        wheelbase_m=2.686,
        track_width_front_m=1.578,
        track_width_rear_m=1.594,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=505,
        torque_nm=637,
        has_aero=False,
        cd_a=0.58,
        stock_tire_size_front="275/35R18",
        stock_tire_size_rear="325/30R19",
        notes="7.0 L LS7 NA V8 (470 lb-ft). Aluminum frame — lighter than base C6.",
    ),
    "chevrolet_corvette_c6_zr1": VehicleSpec(
        make="Chevrolet",
        model="Corvette ZR1",
        generation="C6",
        year_range=(2009, 2013),
        weight_kg=1528,
        wheelbase_m=2.686,
        track_width_front_m=1.594,
        track_width_rear_m=1.600,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=638,
        torque_nm=819,
        has_aero=True,
        cd_a=0.64,
        cl_a=0.60,
        stock_tire_size_front="285/30R19",
        stock_tire_size_rear="335/25R20",
        notes="6.2 L LS9 supercharged V8 (604 lb-ft). Carbon hood + splitter standard.",
    ),
    "chevrolet_corvette_c7_z06": VehicleSpec(
        make="Chevrolet",
        model="Corvette Z06",
        generation="C7",
        year_range=(2015, 2019),
        weight_kg=1525,
        wheelbase_m=2.710,
        track_width_front_m=1.600,
        track_width_rear_m=1.614,
        cg_height_m=0.47,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=650,
        torque_nm=881,
        has_aero=True,
        cd_a=0.71,
        cl_a=0.90,
        stock_tire_size_front="285/30R19",
        stock_tire_size_rear="335/25R20",
        notes="6.2 L LT4 supercharged V8 (650 lb-ft). Z07 aero package adds larger wing.",
    ),
    "chevrolet_corvette_c7_zr1": VehicleSpec(
        make="Chevrolet",
        model="Corvette ZR1",
        generation="C7",
        year_range=(2019, 2019),
        weight_kg=1693,
        wheelbase_m=2.710,
        track_width_front_m=1.597,
        track_width_rear_m=1.611,
        cg_height_m=0.47,
        weight_dist_front_pct=50.0,
        drivetrain="RWD",
        hp=755,
        torque_nm=969,
        has_aero=True,
        cd_a=0.76,
        cl_a=1.20,
        stock_tire_size_front="285/30R19",
        stock_tire_size_rear="335/25R20",
        notes="6.2 L LT5 supercharged V8 (715 lb-ft). Standard high- or low-wing aero.",
    ),
    "chevrolet_corvette_c8_z06": VehicleSpec(
        make="Chevrolet",
        model="Corvette Z06",
        generation="C8",
        year_range=(2023, 2025),
        weight_kg=1507,
        wheelbase_m=2.723,
        track_width_front_m=1.597,
        track_width_rear_m=1.626,
        cg_height_m=0.44,
        weight_dist_front_pct=40.0,
        drivetrain="RWD",
        hp=670,
        torque_nm=637,
        has_aero=True,
        cd_a=0.68,
        cl_a=1.20,
        stock_tire_size_front="275/30R20",
        stock_tire_size_rear="345/25R21",
        notes="5.5 L LT6 flat-plane NA V8 (470 lb-ft). Mid-engine. Z07 adds massive wing.",
        power_band_factor=0.85,
    ),
    "chevrolet_corvette_c8_zr1": VehicleSpec(
        make="Chevrolet",
        model="Corvette ZR1",
        generation="C8",
        year_range=(2025, 2025),
        weight_kg=1678,
        wheelbase_m=2.723,
        track_width_front_m=1.597,
        track_width_rear_m=1.626,
        cg_height_m=0.44,
        weight_dist_front_pct=40.0,
        drivetrain="RWD",
        hp=1064,
        torque_nm=1006,
        has_aero=True,
        cd_a=0.80,
        cl_a=1.80,
        stock_tire_size_front="275/30R20",
        stock_tire_size_rear="345/25R21",
        notes="5.5 L LT7 flat-plane twin-turbo V8 (742 lb-ft). Mid-engine. Standard massive wing.",
    ),
    # -----------------------------------------------------------------------
    # BMW M3 / M2
    # -----------------------------------------------------------------------
    "bmw_m3_e46": VehicleSpec(
        make="BMW",
        model="M3",
        generation="E46",
        year_range=(2001, 2006),
        weight_kg=1570,
        wheelbase_m=2.730,
        track_width_front_m=1.507,
        track_width_rear_m=1.527,
        cg_height_m=0.51,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=333,
        torque_nm=365,
        has_aero=False,
        cd_a=0.69,
        stock_tire_size_front="225/45R18",
        stock_tire_size_rear="255/40R18",
        notes="3.2 L S54 inline-6. Classic track car.",
    ),
    "bmw_m3_f80": VehicleSpec(
        make="BMW",
        model="M3",
        generation="F80",
        year_range=(2014, 2018),
        weight_kg=1585,
        wheelbase_m=2.812,
        track_width_front_m=1.560,
        track_width_rear_m=1.560,
        cg_height_m=0.52,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=425,
        torque_nm=550,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="255/40R18",
        stock_tire_size_rear="275/40R18",
        notes="3.0 L S55 twin-turbo inline-6.",
    ),
    "bmw_m3_g80": VehicleSpec(
        make="BMW",
        model="M3",
        generation="G80",
        year_range=(2021, 2025),
        weight_kg=1730,
        wheelbase_m=2.857,
        track_width_front_m=1.604,
        track_width_rear_m=1.610,
        cg_height_m=0.53,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=473,
        torque_nm=550,
        has_aero=False,
        cd_a=0.77,
        stock_tire_size_front="275/40R18",
        stock_tire_size_rear="285/35R19",
        notes="3.0 L S58 twin-turbo. Competition RWD (DIN weight).",
        power_band_factor=0.95,
    ),
    "bmw_m2_f87": VehicleSpec(
        make="BMW",
        model="M2",
        generation="F87",
        year_range=(2016, 2018),
        weight_kg=1570,
        wheelbase_m=2.693,
        track_width_front_m=1.535,
        track_width_rear_m=1.555,
        cg_height_m=0.51,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=365,
        torque_nm=465,
        has_aero=False,
        cd_a=0.69,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="265/35R19",
        notes="3.0 L N55 turbo. Base M2 (not Competition).",
    ),
    "bmw_m2_g87": VehicleSpec(
        make="BMW",
        model="M2",
        generation="G87",
        year_range=(2023, 2025),
        weight_kg=1710,
        wheelbase_m=2.745,
        track_width_front_m=1.580,
        track_width_rear_m=1.595,
        cg_height_m=0.52,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=453,
        torque_nm=550,
        has_aero=False,
        cd_a=0.71,
        stock_tire_size_front="275/35R19",
        stock_tire_size_rear="285/35R19",
        notes="3.0 L S58 twin-turbo inline-6.",
        power_band_factor=0.95,
    ),
    # -----------------------------------------------------------------------
    # Ford Mustang GT
    # -----------------------------------------------------------------------
    "ford_mustang_gt_s197": VehicleSpec(
        make="Ford",
        model="Mustang GT",
        generation="S197",
        year_range=(2011, 2014),
        weight_kg=1630,
        wheelbase_m=2.720,
        track_width_front_m=1.535,
        track_width_rear_m=1.570,
        cg_height_m=0.52,
        weight_dist_front_pct=55.0,
        drivetrain="RWD",
        hp=420,
        torque_nm=529,
        has_aero=False,
        cd_a=0.75,
        stock_tire_size_front="235/50R18",
        stock_tire_size_rear="235/50R18",
        notes="5.0 L Coyote V8 (2013-14 spec). Solid rear axle.",
        power_band_factor=0.88,
    ),
    "ford_mustang_gt_s550": VehicleSpec(
        make="Ford",
        model="Mustang GT",
        generation="S550",
        year_range=(2015, 2023),
        weight_kg=1720,
        wheelbase_m=2.720,
        track_width_front_m=1.570,
        track_width_rear_m=1.580,
        cg_height_m=0.52,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=460,
        torque_nm=570,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="255/40R19",
        stock_tire_size_rear="275/40R19",
        notes="5.0 L Coyote V8 (420 lb-ft, 2018+ spec). IRS upgrade.",
        power_band_factor=0.88,
    ),
    "ford_mustang_gt_s650": VehicleSpec(
        make="Ford",
        model="Mustang GT",
        generation="S650",
        year_range=(2024, 2025),
        weight_kg=1756,
        wheelbase_m=2.720,
        track_width_front_m=1.576,
        track_width_rear_m=1.587,
        cg_height_m=0.52,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=480,
        torque_nm=563,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="255/40R19",
        stock_tire_size_rear="255/40R19",
        notes="5.0 L Coyote Gen-4 V8 (415 lb-ft).",
        power_band_factor=0.88,
    ),
    # -----------------------------------------------------------------------
    # Porsche
    # -----------------------------------------------------------------------
    "porsche_cayman_987": VehicleSpec(
        make="Porsche",
        model="Cayman",
        generation="987",
        year_range=(2006, 2012),
        weight_kg=1340,
        wheelbase_m=2.415,
        track_width_front_m=1.486,
        track_width_rear_m=1.528,
        cg_height_m=0.45,
        weight_dist_front_pct=46.0,
        drivetrain="RWD",
        hp=295,
        torque_nm=340,
        has_aero=False,
        cd_a=0.56,
        stock_tire_size_front="235/40R18",
        stock_tire_size_rear="265/40R18",
        notes="3.4 L flat-6 (Cayman S). Mid-engine.",
    ),
    "porsche_cayman_718": VehicleSpec(
        make="Porsche",
        model="Cayman",
        generation="718",
        year_range=(2017, 2025),
        weight_kg=1385,
        wheelbase_m=2.475,
        track_width_front_m=1.528,
        track_width_rear_m=1.540,
        cg_height_m=0.45,
        weight_dist_front_pct=44.0,
        drivetrain="RWD",
        hp=300,
        torque_nm=380,
        has_aero=False,
        cd_a=0.59,
        stock_tire_size_front="235/40R19",
        stock_tire_size_rear="265/40R19",
        notes="2.0 L turbo flat-4 (base). GTS has 4.0 flat-6.",
    ),
    "porsche_cayman_gt4_718": VehicleSpec(
        make="Porsche",
        model="Cayman GT4",
        generation="718",
        year_range=(2020, 2025),
        weight_kg=1450,
        wheelbase_m=2.475,
        track_width_front_m=1.524,
        track_width_rear_m=1.544,
        cg_height_m=0.45,
        weight_dist_front_pct=43.0,
        drivetrain="RWD",
        hp=414,
        torque_nm=420,
        has_aero=True,
        cd_a=0.68,
        cl_a=0.55,
        stock_tire_size_front="245/35R20",
        stock_tire_size_rear="295/30R20",
        notes="4.0 L flat-6 NA (shared with 992 GT3). Fixed rear wing.",
    ),
    "porsche_911_gt3_991": VehicleSpec(
        make="Porsche",
        model="911 GT3",
        generation="991.2",
        year_range=(2017, 2019),
        weight_kg=1430,
        wheelbase_m=2.457,
        track_width_front_m=1.531,
        track_width_rear_m=1.540,
        cg_height_m=0.46,
        weight_dist_front_pct=39.0,
        drivetrain="RWD",
        hp=493,
        torque_nm=460,
        has_aero=True,
        cd_a=0.68,
        cl_a=0.65,
        stock_tire_size_front="245/35R20",
        stock_tire_size_rear="305/30R20",
        notes="4.0 L flat-6 NA (500 PS). 991.2 generation. Fixed rear wing.",
    ),
    "porsche_911_gt3_992": VehicleSpec(
        make="Porsche",
        model="911 GT3",
        generation="992",
        year_range=(2021, 2025),
        weight_kg=1435,
        wheelbase_m=2.457,
        track_width_front_m=1.587,
        track_width_rear_m=1.570,
        cg_height_m=0.46,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=502,
        torque_nm=469,
        has_aero=True,
        cd_a=0.68,
        cl_a=0.80,
        stock_tire_size_front="255/35R20",
        stock_tire_size_rear="315/30R21",
        notes="4.0 L flat-6 NA. Swan-neck wing.",
    ),
    # -----------------------------------------------------------------------
    # Nissan
    # -----------------------------------------------------------------------
    "nissan_350z": VehicleSpec(
        make="Nissan",
        model="350Z",
        generation="Z33",
        year_range=(2003, 2009),
        weight_kg=1474,
        wheelbase_m=2.650,
        track_width_front_m=1.524,
        track_width_rear_m=1.534,
        cg_height_m=0.48,
        weight_dist_front_pct=55.0,
        drivetrain="RWD",
        hp=287,
        torque_nm=363,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="225/45R18",
        stock_tire_size_rear="245/45R18",
        notes="3.5 L VQ35DE/HR V6.",
    ),
    "nissan_370z": VehicleSpec(
        make="Nissan",
        model="370Z",
        generation="Z34",
        year_range=(2009, 2020),
        weight_kg=1496,
        wheelbase_m=2.550,
        track_width_front_m=1.540,
        track_width_rear_m=1.555,
        cg_height_m=0.48,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=332,
        torque_nm=366,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="225/50R18",
        stock_tire_size_rear="245/45R18",
        notes="3.7 L VQ37VHR V6 (270 lb-ft).",
    ),
    # -----------------------------------------------------------------------
    # Subaru WRX STI
    # -----------------------------------------------------------------------
    "subaru_wrx_sti_va": VehicleSpec(
        make="Subaru",
        model="WRX STI",
        generation="VA",
        year_range=(2015, 2021),
        weight_kg=1565,
        wheelbase_m=2.650,
        track_width_front_m=1.530,
        track_width_rear_m=1.540,
        cg_height_m=0.54,
        weight_dist_front_pct=60.0,
        drivetrain="AWD",
        hp=310,
        torque_nm=393,
        has_aero=True,
        cd_a=0.72,
        cl_a=0.15,
        stock_tire_size_front="245/40R18",
        stock_tire_size_rear="245/40R18",
        notes="2.5 L EJ257 turbo. DCCD AWD system.",
        power_band_factor=0.92,
    ),
    # -----------------------------------------------------------------------
    # Toyota GR Supra
    # -----------------------------------------------------------------------
    "toyota_gr_supra_a90": VehicleSpec(
        make="Toyota",
        model="GR Supra",
        generation="A90",
        year_range=(2020, 2025),
        weight_kg=1540,
        wheelbase_m=2.470,
        track_width_front_m=1.594,
        track_width_rear_m=1.589,
        cg_height_m=0.48,
        weight_dist_front_pct=48.0,
        drivetrain="RWD",
        hp=382,
        torque_nm=500,
        has_aero=False,
        cd_a=0.64,
        stock_tire_size_front="255/35R19",
        stock_tire_size_rear="275/35R19",
        notes="3.0 L B58 turbo inline-6. BMW Z4 platform.",
    ),
    # -----------------------------------------------------------------------
    # Dodge Challenger SRT
    # -----------------------------------------------------------------------
    "dodge_challenger_srt_392": VehicleSpec(
        make="Dodge",
        model="Challenger SRT 392",
        generation="LC",
        year_range=(2015, 2023),
        weight_kg=1913,
        wheelbase_m=2.946,
        track_width_front_m=1.590,
        track_width_rear_m=1.596,
        cg_height_m=0.55,
        weight_dist_front_pct=57.0,
        drivetrain="RWD",
        hp=485,
        torque_nm=644,
        has_aero=False,
        cd_a=0.88,
        stock_tire_size_front="275/40R20",
        stock_tire_size_rear="275/40R20",
        notes="6.4 L HEMI V8. Heavy muscle car.",
    ),
    # -----------------------------------------------------------------------
    # Chevrolet Camaro
    # -----------------------------------------------------------------------
    "chevrolet_camaro_ss_6th": VehicleSpec(
        make="Chevrolet",
        model="Camaro SS",
        generation="6th Gen",
        year_range=(2016, 2024),
        weight_kg=1680,
        wheelbase_m=2.811,
        track_width_front_m=1.614,
        track_width_rear_m=1.612,
        cg_height_m=0.50,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=455,
        torque_nm=617,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="245/40R20",
        stock_tire_size_rear="275/35R20",
        notes="6.2 L LT1 V8. Alpha platform.",
    ),
    "chevrolet_camaro_zl1_6th": VehicleSpec(
        make="Chevrolet",
        model="Camaro ZL1",
        generation="6th Gen",
        year_range=(2017, 2024),
        weight_kg=1770,
        wheelbase_m=2.811,
        track_width_front_m=1.630,
        track_width_rear_m=1.630,
        cg_height_m=0.50,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=650,
        torque_nm=881,
        has_aero=True,
        cd_a=0.79,
        cl_a=0.35,
        stock_tire_size_front="285/30R20",
        stock_tire_size_rear="305/30R20",
        notes="6.2 L LT4 supercharged V8.",
    ),
    # -----------------------------------------------------------------------
    # Volkswagen GTI
    # -----------------------------------------------------------------------
    "volkswagen_gti_mk7": VehicleSpec(
        make="Volkswagen",
        model="GTI",
        generation="Mk7",
        year_range=(2015, 2021),
        weight_kg=1382,
        wheelbase_m=2.631,
        track_width_front_m=1.535,
        track_width_rear_m=1.510,
        cg_height_m=0.55,
        weight_dist_front_pct=60.0,
        drivetrain="FWD",
        hp=228,
        torque_nm=350,
        has_aero=False,
        cd_a=0.67,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="225/40R18",
        notes="2.0 L EA888 turbo. MQB platform.",
    ),
    "volkswagen_gti_mk8": VehicleSpec(
        make="Volkswagen",
        model="GTI",
        generation="Mk8",
        year_range=(2022, 2025),
        weight_kg=1420,
        wheelbase_m=2.631,
        track_width_front_m=1.543,
        track_width_rear_m=1.515,
        cg_height_m=0.55,
        weight_dist_front_pct=60.0,
        drivetrain="FWD",
        hp=241,
        torque_nm=370,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="235/35R19",
        stock_tire_size_rear="235/35R19",
        notes="2.0 L EA888 Evo4 turbo.",
    ),
    # -----------------------------------------------------------------------
    # Hyundai Veloster N
    # -----------------------------------------------------------------------
    "hyundai_veloster_n": VehicleSpec(
        make="Hyundai",
        model="Veloster N",
        generation="JS",
        year_range=(2019, 2022),
        weight_kg=1391,
        wheelbase_m=2.650,
        track_width_front_m=1.569,
        track_width_rear_m=1.576,
        cg_height_m=0.53,
        weight_dist_front_pct=62.0,
        drivetrain="FWD",
        hp=275,
        torque_nm=353,
        has_aero=False,
        cd_a=0.67,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="225/40R18",
        notes="2.0 L Theta II turbo. eLSD available.",
    ),
    # -----------------------------------------------------------------------
    # Toyota GR Corolla
    # -----------------------------------------------------------------------
    "toyota_gr_corolla": VehicleSpec(
        make="Toyota",
        model="GR Corolla",
        generation="GZEA14H",
        year_range=(2023, 2025),
        weight_kg=1474,
        wheelbase_m=2.640,
        track_width_front_m=1.548,
        track_width_rear_m=1.562,
        cg_height_m=0.53,
        weight_dist_front_pct=60.0,
        drivetrain="AWD",
        hp=300,
        torque_nm=370,
        has_aero=True,
        cd_a=0.72,
        cl_a=0.15,
        stock_tire_size_front="235/40R18",
        stock_tire_size_rear="235/40R18",
        notes="1.6 L G16E-GTS turbo 3-cyl. GR-Four AWD.",
    ),
    # -----------------------------------------------------------------------
    # Lexus
    # -----------------------------------------------------------------------
    "lexus_is_f": VehicleSpec(
        make="Lexus",
        model="IS F",
        generation="XE20",
        year_range=(2008, 2014),
        weight_kg=1715,
        wheelbase_m=2.730,
        track_width_front_m=1.535,
        track_width_rear_m=1.540,
        cg_height_m=0.52,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=416,
        torque_nm=505,
        has_aero=False,
        cd_a=0.69,
        stock_tire_size_front="225/40R19",
        stock_tire_size_rear="255/35R19",
        notes="5.0 L 2UR-GSE V8.",
    ),
    "lexus_rc_f": VehicleSpec(
        make="Lexus",
        model="RC F",
        generation="USC10",
        year_range=(2015, 2025),
        weight_kg=1765,
        wheelbase_m=2.730,
        track_width_front_m=1.535,
        track_width_rear_m=1.545,
        cg_height_m=0.50,
        weight_dist_front_pct=55.0,
        drivetrain="RWD",
        hp=472,
        torque_nm=535,
        has_aero=False,
        cd_a=0.72,
        stock_tire_size_front="255/35R19",
        stock_tire_size_rear="275/35R19",
        notes="5.0 L 2UR-GSE V8. Track Edition available.",
    ),
    # -----------------------------------------------------------------------
    # Lotus
    # -----------------------------------------------------------------------
    "lotus_elise_s2": VehicleSpec(
        make="Lotus",
        model="Elise",
        generation="S2",
        year_range=(2001, 2011),
        weight_kg=860,
        wheelbase_m=2.300,
        track_width_front_m=1.452,
        track_width_rear_m=1.494,
        cg_height_m=0.42,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=189,
        torque_nm=180,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="195/50R16",
        stock_tire_size_rear="225/45R17",
        notes="1.8 L 2ZZ-GE Toyota. Ultralight.",
    ),
    "lotus_exige_s2": VehicleSpec(
        make="Lotus",
        model="Exige",
        generation="S2",
        year_range=(2004, 2011),
        weight_kg=933,
        wheelbase_m=2.300,
        track_width_front_m=1.452,
        track_width_rear_m=1.494,
        cg_height_m=0.42,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=220,
        torque_nm=224,
        has_aero=True,
        cd_a=0.62,
        cl_a=0.30,
        stock_tire_size_front="195/50R16",
        stock_tire_size_rear="225/45R17",
        notes="1.8 L 2ZZ-GE supercharged (165 lb-ft). Fixed roof + wing.",
    ),
    # -----------------------------------------------------------------------
    # Audi
    # -----------------------------------------------------------------------
    "audi_rs3_8v": VehicleSpec(
        make="Audi",
        model="RS3",
        generation="8V",
        year_range=(2017, 2022),
        weight_kg=1555,
        wheelbase_m=2.631,
        track_width_front_m=1.553,
        track_width_rear_m=1.531,
        cg_height_m=0.54,
        weight_dist_front_pct=59.0,
        drivetrain="AWD",
        hp=400,
        torque_nm=480,
        has_aero=False,
        cd_a=0.70,
        stock_tire_size_front="255/30R19",
        stock_tire_size_rear="235/35R19",
        notes="2.5 L TFSI inline-5 turbo. Quattro AWD.",
    ),
    "audi_ttrs_8s": VehicleSpec(
        make="Audi",
        model="TT RS",
        generation="8S",
        year_range=(2018, 2023),
        weight_kg=1515,
        wheelbase_m=2.505,
        track_width_front_m=1.553,
        track_width_rear_m=1.526,
        cg_height_m=0.50,
        weight_dist_front_pct=58.0,
        drivetrain="AWD",
        hp=400,
        torque_nm=480,
        has_aero=False,
        cd_a=0.66,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="245/35R19",
        notes="2.5 L TFSI inline-5 turbo.",
    ),
    # -----------------------------------------------------------------------
    # Mercedes-AMG
    # -----------------------------------------------------------------------
    "mercedes_amg_c63_w205": VehicleSpec(
        make="Mercedes-AMG",
        model="C 63",
        generation="W205",
        year_range=(2015, 2021),
        weight_kg=1770,
        wheelbase_m=2.840,
        track_width_front_m=1.565,
        track_width_rear_m=1.570,
        cg_height_m=0.53,
        weight_dist_front_pct=55.0,
        drivetrain="RWD",
        hp=469,
        torque_nm=650,
        has_aero=False,
        cd_a=0.69,
        stock_tire_size_front="255/35R19",
        stock_tire_size_rear="285/30R19",
        notes="4.0 L M177 twin-turbo V8.",
    ),
    # -----------------------------------------------------------------------
    # Nissan GT-R
    # -----------------------------------------------------------------------
    "nissan_gtr_r35": VehicleSpec(
        make="Nissan",
        model="GT-R",
        generation="R35",
        year_range=(2017, 2024),
        weight_kg=1752,
        wheelbase_m=2.780,
        track_width_front_m=1.590,
        track_width_rear_m=1.600,
        cg_height_m=0.50,
        weight_dist_front_pct=54.0,
        drivetrain="AWD",
        hp=565,
        torque_nm=633,
        has_aero=False,
        cd_a=0.60,
        stock_tire_size_front="255/40R20",
        stock_tire_size_rear="285/35R20",
        notes="3.8 L VR38DETT twin-turbo V6 (2017+ spec). ATTESA E-TS AWD.",
        power_band_factor=0.93,
    ),
    # -----------------------------------------------------------------------
    # Hyundai Elantra N
    # -----------------------------------------------------------------------
    "hyundai_elantra_n": VehicleSpec(
        make="Hyundai",
        model="Elantra N",
        generation="CN7",
        year_range=(2022, 2025),
        weight_kg=1450,
        wheelbase_m=2.720,
        track_width_front_m=1.565,
        track_width_rear_m=1.572,
        cg_height_m=0.53,
        weight_dist_front_pct=62.0,
        drivetrain="FWD",
        hp=276,
        torque_nm=392,
        has_aero=False,
        cd_a=0.63,
        stock_tire_size_front="235/40R18",
        stock_tire_size_rear="235/40R18",
        notes="2.0 L Theta III turbo. Spiritual Veloster N successor.",
    ),
    # -----------------------------------------------------------------------
    # BMW M240i
    # -----------------------------------------------------------------------
    "bmw_m240i_g42": VehicleSpec(
        make="BMW",
        model="M240i",
        generation="G42",
        year_range=(2022, 2025),
        weight_kg=1690,
        wheelbase_m=2.741,
        track_width_front_m=1.575,
        track_width_rear_m=1.585,
        cg_height_m=0.52,
        weight_dist_front_pct=52.0,
        drivetrain="AWD",
        hp=382,
        torque_nm=500,
        has_aero=False,
        cd_a=0.71,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="255/35R19",
        notes="3.0 L B58 turbo inline-6. xDrive AWD.",
    ),
    # -----------------------------------------------------------------------
    # Ford Focus RS
    # -----------------------------------------------------------------------
    "ford_focus_rs_mk3": VehicleSpec(
        make="Ford",
        model="Focus RS",
        generation="Mk3",
        year_range=(2016, 2018),
        weight_kg=1572,
        wheelbase_m=2.648,
        track_width_front_m=1.563,
        track_width_rear_m=1.565,
        cg_height_m=0.54,
        weight_dist_front_pct=62.0,
        drivetrain="AWD",
        hp=350,
        torque_nm=440,
        has_aero=True,
        cd_a=0.78,
        cl_a=0.15,
        stock_tire_size_front="235/35R19",
        stock_tire_size_rear="235/35R19",
        notes="2.3 L EcoBoost turbo. Twin-clutch rear axle.",
    ),
    # -----------------------------------------------------------------------
    # Mazda MazdaSpeed3 / Mazda3 Turbo
    # -----------------------------------------------------------------------
    "mazda_mazdaspeed3": VehicleSpec(
        make="Mazda",
        model="MazdaSpeed3",
        generation="BL",
        year_range=(2010, 2013),
        weight_kg=1490,
        wheelbase_m=2.640,
        track_width_front_m=1.530,
        track_width_rear_m=1.515,
        cg_height_m=0.54,
        weight_dist_front_pct=63.0,
        drivetrain="FWD",
        hp=263,
        torque_nm=380,
        has_aero=False,
        cd_a=0.66,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="225/40R18",
        notes="2.3 L MZR DISI turbo. Torque steer monster.",
    ),
    # -----------------------------------------------------------------------
    # Acura
    # -----------------------------------------------------------------------
    "acura_integra_type_s_de5": VehicleSpec(
        make="Acura",
        model="Integra Type S",
        generation="DE5",
        year_range=(2024, 2025),
        weight_kg=1461,
        wheelbase_m=2.735,
        track_width_front_m=1.591,
        track_width_rear_m=1.579,
        cg_height_m=0.52,
        weight_dist_front_pct=62.0,
        drivetrain="FWD",
        hp=320,
        torque_nm=420,
        has_aero=True,
        cd_a=0.74,
        cl_a=0.20,
        stock_tire_size_front="265/35R19",
        stock_tire_size_rear="265/35R19",
        notes="2.0 L K20C8 turbo. Functional rear wing. Closest modern FWD sport to Civic Type R.",
    ),
    # -----------------------------------------------------------------------
    # Alfa Romeo
    # -----------------------------------------------------------------------
    "alfa_romeo_giulia_qv": VehicleSpec(
        make="Alfa Romeo",
        model="Giulia Quadrifoglio",
        generation="952",
        year_range=(2017, 2025),
        weight_kg=1580,
        wheelbase_m=2.820,
        track_width_front_m=1.572,
        track_width_rear_m=1.580,
        cg_height_m=0.52,
        weight_dist_front_pct=50.0,
        drivetrain="RWD",
        hp=505,
        torque_nm=600,
        has_aero=False,
        cd_a=0.72,
        stock_tire_size_front="245/35R19",
        stock_tire_size_rear="285/30R19",
        notes="2.9 L bi-turbo V6 Ferrari-derived. Carbon driveshaft.",
    ),
    # -----------------------------------------------------------------------
    # BMW 128i / M3 E36 + E92 / M4 F82
    # -----------------------------------------------------------------------
    "bmw_128i_e82": VehicleSpec(
        make="BMW",
        model="128i",
        generation="E82",
        year_range=(2008, 2013),
        weight_kg=1452,
        wheelbase_m=2.660,
        track_width_front_m=1.465,
        track_width_rear_m=1.470,
        cg_height_m=0.52,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=230,
        torque_nm=271,
        has_aero=False,
        cd_a=0.70,
        stock_tire_size_front="205/50R17",
        stock_tire_size_rear="225/45R17",
        notes="3.0 L N52 inline-6. Affordable RWD BMW track car.",
    ),
    "bmw_m3_e36_us": VehicleSpec(
        make="BMW",
        model="M3",
        generation="E36",
        year_range=(1995, 1999),
        weight_kg=1536,
        wheelbase_m=2.700,
        track_width_front_m=1.418,
        track_width_rear_m=1.436,
        cg_height_m=0.52,
        weight_dist_front_pct=51.0,
        drivetrain="RWD",
        hp=240,
        torque_nm=320,
        has_aero=False,
        cd_a=0.66,
        stock_tire_size_front="225/45R17",
        stock_tire_size_rear="245/40R17",
        notes="3.2 L S52 inline-6 (US spec). Detuned vs EUR S50B32.",
    ),
    "bmw_m3_e92": VehicleSpec(
        make="BMW",
        model="M3",
        generation="E92",
        year_range=(2008, 2013),
        weight_kg=1577,
        wheelbase_m=2.761,
        track_width_front_m=1.540,
        track_width_rear_m=1.545,
        cg_height_m=0.52,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=414,
        torque_nm=400,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="245/40R18",
        stock_tire_size_rear="265/40R18",
        notes="4.0 L S65 naturally-aspirated V8. Last NA M3.",
    ),
    "bmw_m4_f82_competition": VehicleSpec(
        make="BMW",
        model="M4",
        generation="F82",
        year_range=(2016, 2020),
        weight_kg=1589,
        wheelbase_m=2.812,
        track_width_front_m=1.585,
        track_width_rear_m=1.575,
        cg_height_m=0.52,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=444,
        torque_nm=550,
        has_aero=False,
        cd_a=0.73,
        stock_tire_size_front="265/30R20",
        stock_tire_size_rear="285/30R20",
        notes='3.0 L S55 twin-turbo Competition. 19/20" wheels.',
    ),
    # -----------------------------------------------------------------------
    # Chevrolet Camaro 1LE
    # -----------------------------------------------------------------------
    "chevrolet_camaro_ss_1le_6g": VehicleSpec(
        make="Chevrolet",
        model="Camaro SS 1LE",
        generation="6th Gen",
        year_range=(2017, 2024),
        weight_kg=1688,
        wheelbase_m=2.811,
        track_width_front_m=1.627,
        track_width_rear_m=1.625,
        cg_height_m=0.49,
        weight_dist_front_pct=52.0,
        drivetrain="RWD",
        hp=455,
        torque_nm=617,
        has_aero=True,
        cd_a=0.75,
        cl_a=0.30,
        stock_tire_size_front="285/30R20",
        stock_tire_size_rear="305/30R20",
        notes="6.2 L LT1 V8. Track-tuned suspension, Brembo brakes, aero package.",
    ),
    # -----------------------------------------------------------------------
    # Ford Mustang Shelby GT350 / Mach 1
    # -----------------------------------------------------------------------
    "ford_mustang_gt350": VehicleSpec(
        make="Ford",
        model="Mustang Shelby GT350",
        generation="S550",
        year_range=(2016, 2020),
        weight_kg=1720,
        wheelbase_m=2.720,
        track_width_front_m=1.596,
        track_width_rear_m=1.602,
        cg_height_m=0.50,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=526,
        torque_nm=582,
        has_aero=True,
        cd_a=0.75,
        cl_a=0.20,
        stock_tire_size_front="295/35R19",
        stock_tire_size_rear="305/35R19",
        notes="5.2 L Voodoo flat-plane V8. MagneRide. Track-focused Mustang.",
    ),
    "ford_mustang_mach1_s550": VehicleSpec(
        make="Ford",
        model="Mustang Mach 1",
        generation="S550",
        year_range=(2021, 2023),
        weight_kg=1755,
        wheelbase_m=2.720,
        track_width_front_m=1.575,
        track_width_rear_m=1.580,
        cg_height_m=0.52,
        weight_dist_front_pct=54.0,
        drivetrain="RWD",
        hp=470,
        torque_nm=556,
        has_aero=True,
        cd_a=0.74,
        cl_a=0.15,
        stock_tire_size_front="255/40R19",
        stock_tire_size_rear="275/40R19",
        notes="5.0 L Coyote V8 (412 lb-ft). Gurney flap + front splitter.",
    ),
    # -----------------------------------------------------------------------
    # Honda S2000 AP2
    # -----------------------------------------------------------------------
    "honda_s2000_ap2": VehicleSpec(
        make="Honda",
        model="S2000",
        generation="AP2",
        year_range=(2004, 2009),
        weight_kg=1270,
        wheelbase_m=2.400,
        track_width_front_m=1.470,
        track_width_rear_m=1.510,
        cg_height_m=0.46,
        weight_dist_front_pct=50.0,
        drivetrain="RWD",
        hp=237,
        torque_nm=220,
        has_aero=False,
        cd_a=0.61,
        stock_tire_size_front="215/45R17",
        stock_tire_size_rear="245/40R17",
        notes="2.2 L F22C1 inline-4. Lower redline (8200 RPM). Wider power band than AP1.",
        power_band_factor=0.80,
    ),
    # -----------------------------------------------------------------------
    # Mitsubishi Lancer Evolution
    # -----------------------------------------------------------------------
    "mitsubishi_evo_ix": VehicleSpec(
        make="Mitsubishi",
        model="Lancer Evolution IX",
        generation="CT9A",
        year_range=(2005, 2007),
        weight_kg=1410,
        wheelbase_m=2.625,
        track_width_front_m=1.480,
        track_width_rear_m=1.480,
        cg_height_m=0.54,
        weight_dist_front_pct=57.0,
        drivetrain="AWD",
        hp=286,
        torque_nm=392,
        has_aero=True,
        cd_a=0.72,
        cl_a=0.15,
        stock_tire_size_front="235/45R17",
        stock_tire_size_rear="235/45R17",
        notes="2.0 L 4G63T. Last 4G63 Evo. MIVEC intake. ACD + AYC AWD.",
    ),
    "mitsubishi_evo_x": VehicleSpec(
        make="Mitsubishi",
        model="Lancer Evolution X",
        generation="CZ4A",
        year_range=(2008, 2016),
        weight_kg=1530,
        wheelbase_m=2.650,
        track_width_front_m=1.510,
        track_width_rear_m=1.510,
        cg_height_m=0.54,
        weight_dist_front_pct=58.0,
        drivetrain="AWD",
        hp=291,
        torque_nm=366,
        has_aero=True,
        cd_a=0.72,
        cl_a=0.15,
        stock_tire_size_front="245/40R18",
        stock_tire_size_rear="245/40R18",
        notes="2.0 L 4B11T. SST or 5MT. ACD + AYC + ABS Sport AWD.",
    ),
    # -----------------------------------------------------------------------
    # Porsche Boxster 986S / 987S
    # -----------------------------------------------------------------------
    "porsche_boxster_986s": VehicleSpec(
        make="Porsche",
        model="Boxster S",
        generation="986",
        year_range=(1999, 2004),
        weight_kg=1320,
        wheelbase_m=2.415,
        track_width_front_m=1.470,
        track_width_rear_m=1.528,
        cg_height_m=0.44,
        weight_dist_front_pct=46.0,
        drivetrain="RWD",
        hp=252,
        torque_nm=310,
        has_aero=False,
        cd_a=0.58,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="265/35R18",
        notes="3.2 L M96/23 flat-6. Mid-engine Porsche entry point.",
    ),
    "porsche_boxster_987s": VehicleSpec(
        make="Porsche",
        model="Boxster S",
        generation="987",
        year_range=(2009, 2012),
        weight_kg=1345,
        wheelbase_m=2.415,
        track_width_front_m=1.478,
        track_width_rear_m=1.534,
        cg_height_m=0.44,
        weight_dist_front_pct=46.0,
        drivetrain="RWD",
        hp=310,
        torque_nm=360,
        has_aero=False,
        cd_a=0.59,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="265/35R18",
        notes="3.4 L M97/23 DFI flat-6 (987.2 gen).",
    ),
    # -----------------------------------------------------------------------
    # Porsche Cayman 981S
    # -----------------------------------------------------------------------
    "porsche_cayman_981s": VehicleSpec(
        make="Porsche",
        model="Cayman S",
        generation="981",
        year_range=(2013, 2016),
        weight_kg=1340,
        wheelbase_m=2.475,
        track_width_front_m=1.532,
        track_width_rear_m=1.516,
        cg_height_m=0.44,
        weight_dist_front_pct=44.0,
        drivetrain="RWD",
        hp=325,
        torque_nm=370,
        has_aero=False,
        cd_a=0.60,
        stock_tire_size_front="235/35R19",
        stock_tire_size_rear="265/35R19",
        notes="3.4 L MA1/23 flat-6. Best-balanced Cayman generation.",
    ),
    # -----------------------------------------------------------------------
    # Porsche Cayman GT4 981
    # -----------------------------------------------------------------------
    "porsche_cayman_gt4_981": VehicleSpec(
        make="Porsche",
        model="Cayman GT4",
        generation="981",
        year_range=(2015, 2016),
        weight_kg=1340,
        wheelbase_m=2.475,
        track_width_front_m=1.532,
        track_width_rear_m=1.516,
        cg_height_m=0.44,
        weight_dist_front_pct=44.0,
        drivetrain="RWD",
        hp=385,
        torque_nm=420,
        has_aero=True,
        cd_a=0.68,
        cl_a=0.50,
        stock_tire_size_front="245/35R20",
        stock_tire_size_rear="295/30R20",
        notes="3.8 L MA1/77 flat-6 NA from 991 Carrera S. GT3-derived suspension. Manual only.",
    ),
    # -----------------------------------------------------------------------
    # Porsche 911 Carrera — 996 / 997.2 S / 991.2 S / 992 S
    # -----------------------------------------------------------------------
    "porsche_911_996": VehicleSpec(
        make="Porsche",
        model="911 Carrera",
        generation="996",
        year_range=(1998, 2004),
        weight_kg=1345,
        wheelbase_m=2.350,
        track_width_front_m=1.455,
        track_width_rear_m=1.500,
        cg_height_m=0.47,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=315,
        torque_nm=370,
        has_aero=False,
        cd_a=0.60,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="285/30R18",
        notes="3.4 L M96 flat-6. First water-cooled 911. IMS bearing risk.",
    ),
    "porsche_911_997s": VehicleSpec(
        make="Porsche",
        model="911 Carrera S",
        generation="997.2",
        year_range=(2009, 2012),
        weight_kg=1425,
        wheelbase_m=2.350,
        track_width_front_m=1.486,
        track_width_rear_m=1.516,
        cg_height_m=0.47,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=385,
        torque_nm=420,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="235/35R19",
        stock_tire_size_rear="295/30R19",
        notes="3.8 L M97/75 DFI flat-6. PASM standard. 997.2 revised.",
    ),
    "porsche_911_991s": VehicleSpec(
        make="Porsche",
        model="911 Carrera S",
        generation="991.2",
        year_range=(2016, 2019),
        weight_kg=1430,
        wheelbase_m=2.450,
        track_width_front_m=1.534,
        track_width_rear_m=1.516,
        cg_height_m=0.47,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=420,
        torque_nm=500,
        has_aero=False,
        cd_a=0.62,
        stock_tire_size_front="245/35R20",
        stock_tire_size_rear="295/30R20",
        notes="3.0 L turbocharged flat-6. 991.2 gen. PDK or 7MT.",
    ),
    "porsche_911_992s": VehicleSpec(
        make="Porsche",
        model="911 Carrera S",
        generation="992",
        year_range=(2019, 2025),
        weight_kg=1535,
        wheelbase_m=2.450,
        track_width_front_m=1.568,
        track_width_rear_m=1.529,
        cg_height_m=0.47,
        weight_dist_front_pct=38.0,
        drivetrain="RWD",
        hp=443,
        torque_nm=530,
        has_aero=False,
        cd_a=0.64,
        stock_tire_size_front="245/35R20",
        stock_tire_size_rear="305/30R21",
        notes="3.0 L turbocharged flat-6. Wider body standard.",
    ),
    # -----------------------------------------------------------------------
    # Subaru BRZ (ZC6 / ZD8) + WRX VA
    # -----------------------------------------------------------------------
    "subaru_brz_zc6": VehicleSpec(
        make="Subaru",
        model="BRZ",
        generation="ZC6",
        year_range=(2013, 2021),
        weight_kg=1247,
        wheelbase_m=2.570,
        track_width_front_m=1.520,
        track_width_rear_m=1.540,
        cg_height_m=0.46,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=200,
        torque_nm=205,
        has_aero=False,
        cd_a=0.52,
        stock_tire_size_front="215/45R17",
        stock_tire_size_rear="215/45R17",
        notes="2.0 L FA20 boxer. Also sold as Toyota 86 / Scion FR-S.",
    ),
    "subaru_brz_zd8": VehicleSpec(
        make="Subaru",
        model="BRZ",
        generation="ZD8",
        year_range=(2022, 2025),
        weight_kg=1275,
        wheelbase_m=2.575,
        track_width_front_m=1.520,
        track_width_rear_m=1.550,
        cg_height_m=0.46,
        weight_dist_front_pct=53.0,
        drivetrain="RWD",
        hp=228,
        torque_nm=249,
        has_aero=False,
        cd_a=0.54,
        stock_tire_size_front="215/45R17",
        stock_tire_size_rear="215/45R17",
        notes="2.4 L FA24 boxer. Also sold as Toyota GR86.",
    ),
    "subaru_wrx_va": VehicleSpec(
        make="Subaru",
        model="WRX",
        generation="VA",
        year_range=(2015, 2021),
        weight_kg=1452,
        wheelbase_m=2.650,
        track_width_front_m=1.530,
        track_width_rear_m=1.540,
        cg_height_m=0.54,
        weight_dist_front_pct=60.0,
        drivetrain="AWD",
        hp=268,
        torque_nm=350,
        has_aero=False,
        cd_a=0.68,
        stock_tire_size_front="235/45R17",
        stock_tire_size_rear="235/45R17",
        notes="2.0 L FA20DIT turbo. Symmetrical AWD. Non-STI model.",
    ),
    # -----------------------------------------------------------------------
    # Toyota MR2 Spyder
    # -----------------------------------------------------------------------
    "toyota_mr2_spyder_zzw30": VehicleSpec(
        make="Toyota",
        model="MR2 Spyder",
        generation="ZZW30",
        year_range=(2000, 2007),
        weight_kg=975,
        wheelbase_m=2.450,
        track_width_front_m=1.435,
        track_width_rear_m=1.470,
        cg_height_m=0.44,
        weight_dist_front_pct=42.0,
        drivetrain="RWD",
        hp=138,
        torque_nm=171,
        has_aero=False,
        cd_a=0.61,
        stock_tire_size_front="185/55R15",
        stock_tire_size_rear="215/45R16",
        notes="1.8 L 1ZZ-FED. Mid-engine open-top. Snap oversteer characteristic.",
    ),
    # -----------------------------------------------------------------------
    # Volkswagen Golf R
    # -----------------------------------------------------------------------
    "volkswagen_golf_r_mk7": VehicleSpec(
        make="Volkswagen",
        model="Golf R",
        generation="Mk7",
        year_range=(2014, 2020),
        weight_kg=1483,
        wheelbase_m=2.631,
        track_width_front_m=1.541,
        track_width_rear_m=1.519,
        cg_height_m=0.55,
        weight_dist_front_pct=61.0,
        drivetrain="AWD",
        hp=292,
        torque_nm=380,
        has_aero=False,
        cd_a=0.67,
        stock_tire_size_front="225/40R18",
        stock_tire_size_rear="225/40R18",
        notes="2.0 L EA888 turbo. 4MOTION AWD. Mk7/7.5 combined.",
    ),
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def find_vehicle(
    make: str,
    model: str,
    generation: str | None = None,
) -> VehicleSpec | None:
    """Find a vehicle spec by make/model/generation.

    Matching is case-insensitive.  If *generation* is ``None``, returns the
    first match for the given make/model (typically the newest generation).

    Args:
        make: Manufacturer name (e.g. ``"Mazda"``).
        model: Model name (e.g. ``"Miata"``).
        generation: Optional generation code (e.g. ``"ND"``).

    Returns:
        The matching :class:`VehicleSpec` if found, otherwise ``None``.
    """
    make_lower = make.lower()
    model_lower = model.lower()
    gen_lower = generation.lower() if generation else None

    for spec in VEHICLE_DATABASE.values():
        if spec.make.lower() != make_lower:
            continue
        if spec.model.lower() != model_lower:
            continue
        if gen_lower is not None and spec.generation.lower() != gen_lower:
            continue
        return spec
    return None


def search_vehicles(query: str, limit: int = 20) -> list[VehicleSpec]:
    """Fuzzy search vehicles by make, model, or generation.

    Performs case-insensitive substring matching against the make, model,
    and generation fields.

    Args:
        query: Substring to match against make, model, or generation.
        limit: Maximum number of results to return.

    Returns:
        Matching :class:`VehicleSpec` entries, up to *limit*.
    """
    if not query:
        return []

    q = query.lower()
    matches: list[VehicleSpec] = []
    for spec in VEHICLE_DATABASE.values():
        if (
            q in spec.make.lower()
            or q in spec.model.lower()
            or q in spec.generation.lower()
            or (spec.notes is not None and q in spec.notes.lower())
        ):
            matches.append(spec)
            if len(matches) >= limit:
                break
    return matches


def list_makes() -> list[str]:
    """List all available makes, sorted alphabetically.

    Returns:
        Deduplicated list of manufacturer names.
    """
    makes = sorted({spec.make for spec in VEHICLE_DATABASE.values()})
    return makes


def list_models(make: str) -> list[str]:
    """List all models for a given make, sorted alphabetically.

    Matching is case-insensitive.

    Args:
        make: Manufacturer name (e.g. ``"BMW"``).

    Returns:
        Deduplicated list of model names for the given make.
    """
    make_lower = make.lower()
    models = sorted(
        {spec.model for spec in VEHICLE_DATABASE.values() if spec.make.lower() == make_lower}
    )
    return models


def get_vehicle_by_slug(slug: str) -> VehicleSpec | None:
    """Look up a vehicle by its exact database slug.

    Args:
        slug: Database key such as ``"mazda_miata_nd"``.

    Returns:
        The :class:`VehicleSpec` if found, otherwise ``None``.
    """
    return VEHICLE_DATABASE.get(slug)


def list_all_vehicles() -> list[VehicleSpec]:
    """Return all vehicles sorted by make, then model, then generation.

    Returns:
        All :class:`VehicleSpec` entries in the database.
    """
    return sorted(
        VEHICLE_DATABASE.values(),
        key=lambda v: (v.make, v.model, v.generation),
    )
